import type { Metadata } from "next";
import localFont from "next/font/local";
import React from "react";
import "./globals.css";
import { Toaster } from "sonner";

const primary = localFont({
    src: "../../public/fonts/primaryfont.woff2",
    variable: "--font-primary",
});

const secondary = localFont({
    src: "../../public/fonts/secondaryfont.woff2",
    variable: "--font-secondary",
});

export const metadata: Metadata = {
    title: "Tekpack Solutions",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${primary.variable} ${secondary.variable} h-full antialiased`}
        >
            <body className="font-primary text-foreground/75 flex min-h-full flex-col">
                {children}
                <Toaster position="bottom-right" richColors />
            </body>
        </html>
    );
}
